name: "Build and Test"

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  test:
    name: "Test"
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 'Setup Node.js'
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Cache pnpm modules
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-

     - name: Install pnpm
        if: ${{ matrix.node-version != '14.x' }}
        uses: pnpm/action-setup@v2.2.4

      - name: Install pnpm (node 14)
        if: ${{ matrix.node-version == '14.x' }}
        run: npm install -g @pnpm/exe@8.1.0

      - name: Install dependencies
        run: pnpm i

      - name: Build
        run: pnpm build

      - name: "Type Check"
        run: pnpm type-check


